In [51]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [4]:
pd.__version__

'2.3.2'

In [5]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [10]:
df.shape[0]

9704

In [16]:
df['fuel_type'].str.lower().unique()

array(['gasoline', 'diesel'], dtype=object)

In [22]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [28]:
df[(df['origin'] == 'Asia') & (df['fuel_efficiency_mpg'] == df.loc[df['origin'] == 'Asia', 'fuel_efficiency_mpg'].max())]

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
9387                  330            3.0       136.0     1223.298226   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
9387           NaN        2001   Asia  Gasoline  Front-wheel drive        1.0   

      fuel_efficiency_mpg  
9387            23.759123

In [31]:
df['horsepower'].mean()

np.float64(149.65729212983547)

In [32]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [33]:
mode_value = df['horsepower'].mode()[0]
mode_value

np.float64(152.0)

In [36]:
df['horsepower'] = df['horsepower'].fillna(mode_value)

In [37]:
df['horsepower'].mean()

np.float64(152.0)

In [39]:
df[df['origin'] == 'Asia']

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       152.0     2714.219310   
12                    320            5.0       152.0     2783.868974   
14                    200            6.0       152.0     3582.687368   
20                    150            3.0       152.0     2231.808142   
21                    160            4.0       152.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0       152.0     3948.404625   
9692                  180            3.0       152.0     3680.341381   
9693                  280            2.0       152.0     2545.070139   
9698                  180            1.0       152.0     3107.427820   
9703                  270            3.0       152.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [40]:
df_asia = df[df['origin'] == 'Asia']

In [41]:
df_asia.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       152.0     2714.219310   
12                  320            5.0       152.0     2783.868974   
14                  200            6.0       152.0     3582.687368   
20                  150            3.0       152.0     2231.808142   
21                  160            4.0       152.0     2659.431451   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14            11.871091  
20            18.889083  
21            16.077730

In [47]:
df_asia[['vehicle_weight', 'model_year']].head(n=7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [56]:
df_asia[['vehicle_weight', 'model_year']].head(n=7).values

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [96]:
X = df_asia[['vehicle_weight', 'model_year']].head(n=7).values

In [97]:
X.shape

(7, 2)

In [98]:
X.T @ X

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [99]:
XTX = X.T @ X
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [100]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [101]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [102]:
X.T.shape

(2, 7)

In [105]:
w = XTX_inv @ X.T @ y

In [106]:
w

array([0.01386421, 0.5049067 ])

In [107]:
w.sum()

np.float64(0.5187709081074016)